language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6"


install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .
  - pip install requests-mock==1.4.0

script:
  - python setup.py test
